### PR TITLE
*Fixed #25 - Better image upload response status check

### LINKED ISSUE #25: Am i the only one struggling with the image/upload?
Love the WYSIWYG however naturally I dont want to upload my images to your webserver and am finding the documentation confusion... where can i change the settings for this so that it uploads new images to my server and it browses my own webserver for already uploaded images?

### PR DESCRIPTION
**Pull request by dannystyleart**
Fixes #25

### CODE REVIEW

**Comment by xdan** [comment]
Thank you!

**Comment by dannystyleart** [comment]
@xdan I forgot to bump the versions and make the latest tag. Could you do it for me?

**Comment by xdan** [comment]
Done!)

**Comment by dannystyleart** [comment]
Thx :beer:

**Pull request merged**
