### PR TITLE
Swap onDelete callback order

### PR DESCRIPTION
**Pull request by jessicarobins**
So that inseparable elements with text as children get deleted

This is related to a `mention` feature I'm building. Basically, I want the entire element to be deleted, but it isn't being deleted because the characters inside it are being deleted instead.

Before:
Screen Recording 2020-07-27 at 03 40 PM

After:
Screen Recording 2020-07-27 at 03 39 PM

### CODE REVIEW

**Comment by xdan** [comment]
@jessicarobins Thanks for your pull request, I would like to accept it, but I think that the expected behavior is that only one character is removed and not the entire element. The rest of the editors work the same way. If you really need this behavior, you can add an option to the `delete` plugin and I will accept the PR

**Comment by jessicarobins** [comment]
Hey @xdan , thanks for looking at my PR! 😄 

That makes sense to me - I was looking at the `INSEPARABLE_TAGS` list and it seemed like most of them were self-closing, so this change would only affect people using a `<jodit></jodit>` tag in their own code. But are you saying that people should also be able to edit the inside of `<script>` and `<iframe>` tags?

This PR was a bit of a quick-fix for me so I could continue with my work but I would think the better solution would be to add some kind of data-attribute that would operate like `contenteditable="false"`. So like, an element with `data-jodit-contenteditable="false"` or `data-jodit-removeable` or something would still have styling applied to it but would be removed all at once instead of being allowed to edit the text inside. That would allow any element to be deleted all at once. Someone requested similar in this comment: https://github.com/xdan/jodit/issues/222#issuecomment-573642561

Do you think that is a good path forward? If so, I can try to implement it.

**Comment by xdan** [comment]
@jessicarobins Yes, if the element has contenteditable = "false" then it must be deleted entirely. I would be grateful if you do this logic.

**Comment by jessicarobins** [comment]
@xdan I will try! The issue I'm running into is that I can't use `contenteditable="false"` in my use case because I still want to be able to modify the css of the the thing I want to remove all at once. When I try to nest contenteditable false like that, the styling gets applied all around the element but not to the element. From what I can tell, this is default browser behavior from the `execCommand` function?

So like, for example, if I had html like 
```
<div>check out  <a contenteditable="false" href="foo.com">this cool thing</a> on my website</div>
```
 and I select all the text and try to make it bold, the result I get is:
```
<div><strong>check out</strong>  <a contenteditable="false" href="foo.com">this cool thing</a> <strong>on my website</strong></div>
```
but the result I want is more like:
```
<div><strong>check out  <a contenteditable="false" href="foo.com">this cool thing</a> on my website</strong></div>
```

So that prevents me from using `"contenteditable="false"` in this case. I think that is probably a common use case, so I'm thinking in addition to checking for `contenteditable="false"` it would be good to have another data attribute that would signal the element needed to be deleted entirely but styles would still be applied.

**Comment by rockwood** [comment]
@jessicarobins I'm working on a similar feature and was running into the same issues. I ended up using css :before pseudo elements to populate the content of the tag.  

In my plugin, I have:

```js
let text = "something"
editor.selection.insertHTML(`<span class="placeholder" title="${text}"></span>`);
```

Then in my css, I use a pseudo element to populate the span using the title attribute.

```css
.placeholder:after {
  content: attr(title);
  background: black;
  color: white;
}
```

That seems to solve the deletion issue. There are still some issues around the cursor placement that I believe would be solved by what you're proposing.

**Comment by jessicarobins** [comment]
@rockwood Thanks for the info! I hadn't thought of using a pseudoelement for that. That's a cool trick.
Re: cursor placement, I had noticed that as well. I couldn't pinpoint the specific place in the code it's happening but it seems like the cursor is automatically moved inside the closest element. I had to do some correction for that:

```
  private onSelectionChange = () => {
    const current = this.jodit.selection.current();
    const parentElement = current?.parentElement;
    const dataId = parentElement?.getAttribute('data-id');

    if (parentElement && dataId === JODIT_DATA_ID) {
      this.jodit.selection.setCursorAfter(parentElement);
    }
  };
```

Here is the full gist of what I wrote: https://gist.github.com/jessicarobins/c572a8bfbbf9ebc17ce62f14d83c9a45 As far as I can tell, it's a working solution (after this PR is merged)

**Comment by jessicarobins** [comment]
@xdan closing this as I see you've implemented my original solution from the first commit here https://github.com/xdan/jodit/commit/5d0ab1e749569b81a654da6083e4a27f02ef1be4

**Pull request closed without merging**
