### PR TITLE
Class span

### PR DESCRIPTION
**Pull request by s-renier-taonix-fr**
Hi!

Here is my new contribution to the Jodit project.
It is a new plugin, which adds a button in the toolbar, allowing to apply a css class name on a selection.
The selected text is automatically wrapped with a span tag (default).

The user must first configure his list of class names that can be used to be able to use this button.
So, I added test class names in the example page: index.html.

I got a lot of inspiration from the "font" plugin and the files it uses like "core / selection / style / *".
I think a good chunk of this code could therefore be factored but I don't have sufficient TypeScript / JavaScript skills to do that.

The corresponding acceptance tests have been written.
Everything is OK.

For the tooltip translations, I used Google Translate.
So it may not be perfect.

I created an svg pictogram for that but you are free to replace it.
My graphic design skills are also quite limited.

Enjoy.
And merry Christmas!

### CODE REVIEW

**Comment by xdan** [comment]
Hi @s-renier-taonix-fr, thanks for your PR. Please do not embed the ./build folder in your PRs. Only TS / LESS files, etc. Conflicts will inevitably arise.

**Comment by s-renier-taonix-fr** [comment]
Oh ! Ok !
Sorry for that !

I think it's ok now.
But I'm not sur about my procedure.
I add a commit with a reset of the file.

I also merge my branch with your master.

Let me known if I need to do something else.

**Comment by s-renier-taonix-fr** [comment]
Hi @xdan, I think my PR are ready to merge into master, isn't it ?

**Comment by xdan** [comment]
@s-renier-taonix-fr Thanks, merged in 3.6.1

**Pull request closed without merging**
